### ISSUE TITLE
Jwt

### ISSUE THREAD

**Issue by fidel-bello** [anthony-fdez/php-blog#1]
- have you figured out the jwt and composer issue?

**Comment by anthony-fdez** [comment]
Yessir, and guess what. I didn't even change nothing, i stoped trying last night and when I got back again this morning it was working. Ridiculous

**Comment by fidel-bello** [comment]
Yes that's crazy! Well, at now you can keep working. I will pull this as well since I need practice with php

**Comment by anthony-fdez** [comment]
Yeah bro if you pull just a warning. It's a mess all around lol. I gotta clean things up

**Comment by fidel-bello** [comment]
Haha! No worries!
